### ISSUE TITLE
Uncaught TypeError: editor.getTabLength is not a function

### ISSUE THREAD

**Issue by rugk** [jamesmacfie/space-tab#19]
[Enter steps to reproduce below:]

This was given me when I tried to edit the settings of the disabled package tree-view-background (at least it was a kind of disabled: https://github.com/KoharaKazuya/tree-view-background/issues/4) with an path in the config which didn't existed.
I deleted these one and when I tried to press AltGr+(key right of 0) which is the key for \ on a QUERTZ layout.

**Atom Version**: 1.0.15
**System**: ASROCK-PC
**Thrown From**: [space-tab](https://github.com/jamesmacfie/space-tab) package, v0.4.2

### Stack Trace

Uncaught TypeError: editor.getTabLength is not a function

```
At D:\Users\%username%\.atom\packages\space-tab\lib\space-tab.coffee:44

TypeError: editor.getTabLength is not a function
  at Object.module.exports.convertToSpaces (D:\Users\%username%\.atom\packages\space-tab\lib\space-tab.coffee:27:23)
  at atom-workspace.<anonymous> (D:\Users\%username%\.atom\packages\space-tab\lib\space-tab.coffee:4:74)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -9:06.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
  2x -8:51.8.0 core:confirm (input.hidden-input)
  3x -4:09.1.0 core:backspace (input.hidden-input)
     -3:59.7.0 command-palette:toggle (div.settings-view.pane-item)
     -3:56 core:confirm (input.hidden-input)
     -3:56 tree-view-background:select (div.settings-view.pane-item)
     -3:54.4.0 core:confirm (div.settings-view.pane-item)
     -3:52.6.0 core:cancel (div.settings-view.pane-item)
  3x -2:39.2.0 core:backspace (input.hidden-input)
  2x -2:13.9.0 window:toggle-dev-tools (button.btn.icon.enablement.icon-playback-play)
  6x -0:33.4.0 core:backspace (input.hidden-input)
     -0:09.9.0 core:select-all (input.hidden-input)
     -0:09.4.0 core:paste (input.hidden-input)
     -0:08.2.0 space-tab:convert-to-spaces (input.hidden-input)
     -0:06.7.0 core:backspace (input.hidden-input)
     -0:06.1.0 space-tab:convert-to-spaces (input.hidden-input)
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "metrics",
      [...]
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.10.1
markdown-preview-opener, v0.1.1
markdown-scroll-sync, v0.4.2
minimap, v4.13.3
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
php-cs-fixer, v2.4.0
space-tab, v0.4.2
switcheroo, v1.1.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by antage** [comment]
I get the same error when I am trying to convert tabs to spaces:

```
/home/antage/.atom/packages/space-tab/lib/space-tab.coffee:27

TypeError: editor.getTabLength is not a function
    at Object.convertToSpaces (/home/antage/.atom/packages/space-tab/lib/space-tab.coffee:27:23)
    at atom-workspace.<anonymous> (/home/antage/.atom/packages/space-tab/lib/space-tab.coffee:4:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```
Atom 1.18.0.
OS: Linux Debian 9 amd64.
space-tab 0.4.2

**Comment by adammenges** [comment]
Same here

<img width="675" alt="image" src="https://user-images.githubusercontent.com/817438/49609678-11bbfd00-f951-11e8-9a11-7b0514f009a5.png">
