### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by MrLeeh** [jamesmacfie/space-tab#3]
My Atom crashes if I use backslashes in the Settings tab. My System is Windows 7 so a backslash is common as a path seperator. I tested the following settings and it crashed:

* Project home
* Linter-pyling setting Executable.

Greetings

**Atom Version**: 0.169.0
**System**: 2354-2187
**Thrown From**: [space-tab](https://github.com/jamesmacfie/space-tab) package, v0.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At c:\Users\Lehmann\.atom\packages\space-tab\lib\space-tab.coffee:27

TypeError: undefined is not a function
  at Object.module.exports.convertToSpaces (c:\Users\Lehmann\.atom\packages\space-tab\lib\space-tab.coffee:27:23)
  at atom-workspace.<anonymous> (c:\Users\Lehmann\.atom\packages\space-tab\lib\space-tab.coffee:4:65)
  at atom-workspace.handler (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\Lehmann\AppData\Local\atom\app-0.169.0\resources\app\src\window-event-handler.js:167:20)

```

### Commands

```
     -0:08.1 command-palette:toggle (atom-text-editor.editor)
     -0:06.3 core:confirm (atom-text-editor.editor.mini)
     -0:06.3 settings-view:open (atom-text-editor.editor)
     -0:00.0 space-tab:convert-to-spaces (atom-text-editor#core.projectHome.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3
color-picker, v1.2.6
indent-guide-improved, v1.0.0
language-restructuredtext, v0.2.0
linter, v0.9.1
linter-pylint, v0.2.0
minimap, v3.5.4
script, v2.16.0
space-tab, v0.1.0
Sublime-Style-Column-Selection, v1.1.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by adrxlm** [comment]
Same issue for me on Windows 7 x64

`Uncaught TypeError: undefined is not a function`

### Stack Trace

```
C:\Users\..\.atom\packages\space-tab\lib\space-tab.coffee:27
Hide Stack Trace
TypeError: undefined is not a function
  at Object.module.exports.convertToSpaces (C:\Users\..\.atom\packages\space-tab\lib\space-tab.coffee:27:23)
  at atom-workspace.<anonymous> (C:\Users\..\.atom\packages\space-tab\lib\space-tab.coffee:4:74)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\..\AppData\Local\atom\app-0.204.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Stack Trace
