### ISSUE TITLE
Failed to activate the space-tab package

### ISSUE THREAD

**Issue by nicolai86** [jamesmacfie/space-tab#9]
Upgrade to atom 0.192.0

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [space-tab](https://github.com/jamesmacfie/space-tab) package, v0.1.0

### Stack Trace

Failed to activate the space-tab package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/nicolai86/.atom/packages/space-tab/lib/space-tab.coffee:4:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:298:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "welcome"
    ]
  }
}
```

### Installed Packages

```coffee
# User
expand-selection-to-quotes, v0.1.0
linter-jscs, v1.10.0
quick-move-file, v0.7.0
space-tab, v0.1.0

# Dev
No dev packages
```

**Comment by jamesmacfie** [comment]
Fixed in v0.3.0. Thanks
